import logotest from  "../pic/logo-new.png";
const BlogApi = [
  {
    id: 1,
    image: "https://drive.google.com/uc?id=1XWzKXbhRfwc6NmFPKuqmi3Wn6d1POjMD",
    date: "2 May, 2021",
    title_one: "คอนเวเยอร์ Conveyor.",
    desc_one: "ผู้ผลิต จำหน่าย และนำเข้า เครื่องจักรอุปกรณ์และนวัตกรรมด้านการขนส่งลำเลียง ระบบจัดเก็บสินค้า ระบบชั้นวางสินค้าอุตสาหกรรม และงานโลจิสติกส์ สร้างไลน์การผลิต (Production Line) ไลน์คอนเวเยอร์ (Conveyor line) โดยมืออาชีพ อย่างครบวงจรตั้งแต่เริ่มต้นจนเสร็จสิ้น",
    title_two: "● ติดตั้งและออกแบบสายพานลำเลียง ตามแบบทุกชนิด ทุกสเป็ค ทุกรูปแบบ ",
    desc_two: "● สายพานลำเลียง (conveyer belt) ",
    title_three: "● สายพานกะพ้อ elevator belt mini belt conveyer wire belt",
    desc_three: "● บริการตัดต่อสายพาน pvc belt conveyer lfda pvc pu rubber assembly line belt conveyer (pvc plastic) wire mesh belt conveyer (stainless steel)",
    // desc_four: "● สายพานลำเลียง (conveyer belt)",
    image3: "https://www.phopautomation.co.th/images/products/Conveyor.jpg",
  },
  {
    id: 2,
    image: "https://www.phopautomation.co.th/images/slide/rack.png",
    date: "28 April, 2021",
    title_one: "ชั้นวางสินค้าอุตสาหกรรม Heavy Rack.",
    desc_one: "บริการออกแบบผลิต ชั้นวางสินค้าอุตสาหกรรม ชั้นเก็บสินค้า,ชั้นวางของ,ชั้นสต็อกสินค้า,ชั้นเก็บของ ชั้นวางอะไหล่ และวางสินค้าทั่วไป ผู้ผลิตและจัดจำหน่ายชั้นวางสินค้า รับปรึกษาฟรี",
    title_two: "● ไมโครแร็ค (Micro Rack) ",
    desc_two: "● มีเดียมแร็ค (Medium Rack) ",
    title_three: "● เฮฟวี่แร็ค (Heavy Rack)",
    // desc_three: "● บริการตัดต่อสายพาน pvc belt conveyer lfda pvc pu rubber assembly line belt conveyer (pvc plastic) wire mesh belt conveyer (stainless steel)",
    // desc_four: "● สายพานลำเลียง (conveyer belt)",
    image3: "https://drive.google.com/uc?id=11wUxRkmjIvVV3wwxPe4UbEi4fD3-KjRi",
  },
  {
    id: 3,
    image: "https://www.phopautomation.co.th/images/slide/machine.png",
    date: "20 Jun, 2021",
    title_one: "หม้อต้มไอน้ำ (Boiler)",
    desc_one: "Water Tube Boiler (หม้อต้มไอน้ำ) เป็นระบบ หม้อต้มไอน้ำ แบบแยกน้ำเผาให้ความร้อน ซึ่งจะช่วยประหยัดเชื้อเพลิงมากข้น และให้ความร้อนเร็ว กว่าระบบหม้อต้มไอน้ำ เชื้อเพลิงที่ใช้ในการเผาไหม้ คือ แก๊ส ไม้ ถ่านหิน ประโยชน์ เครื่องนี้ผลิตไอน้ำได้คงที่และรวดเร็ว พร้อมทั้งให้ความร้อนสูง เหมาะกับ โรงงานอุตสาหกรรม โรงแรม โรงพยาบาล เกี่ยวกับล้างเครื่องมือทางการแพทย์ หรือจะเป็นโรงอบไม้ให้แห้ง ห้องอบที่ใช้ไอน้ำให้ความร้อน",
    // title_two: "Nobis eleifend option conguenes.",
    // desc_two: "Mauris tempor, orci id pellentesque convallis, massa mi congue eros, sed posuere massa nunc quis dui. Integer ornare varius mi, in vehicula orci scelerisque sed. Fusce a massa nisi. Curabitur sit amet suscipit nisl. Sed eget nisl laoreet, suscipit enim nec, viverra eros. Nunc imperdiet risus leo, in rutrum erat dignissim id. Ut rhoncus vestibulum facilisis. Duis et lorem vitae ligula cursus venenatis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc vitae nisi tortor. Morbi leo nulla, posuere vel lectus a, egestas posuere lacus. Fusce eleifend hendrerit bibendum. Morbi nec efficitur ex.",
    // title_three: "Mauris tempor, orci id pellentesque.",
    // desc_three: "Nulla non ligula vel nisi blandit egestas vel eget leo. Praesent fringilla dapibus dignissim. Pellentesque quis quam enim. Vestibulum ultrices, leo id suscipit efficitur, odio lorem rhoncus dolor, a facilisis neque mi ut ex. Quisque tempor urna a nisi pretium, a pretium massa tristique. Nullam in aliquam diam. Maecenas at nibh gravida, ornare eros non, commodo ligula. Sed efficitur sollicitudin auctor. Quisque nec imperdiet purus, in ornare odio. Quisque odio felis, vestibulum et.",
    image3: "https://www.phopautomation.co.th/images/products/WaterTubeBoiler.jpg",
  },
  {
    id: 4,
    image: "https://www.phopautomation.co.th/images/slide/Program.png",
    date: "2 May, 2021",
    title_one: "รับออกแบบโปรแกรม Program Control",
    desc_one: "AUTOMATION",
    title_two: "PROGRAMING AND CONTROL PANAL (โปรแกรมและตู้คอนโทรล) ออกแบบ ติดตั้ง เขียนโปรแกรมควบคุมเครื่องจักร และ โปรแกรมใช้งานทั่วไป",
    image2: "https://www.phopautomation.co.th/images/products/autometion.jpg",
    desc_two: "● วางระบบความคุมและ Monitor การทำงานของ Air Chiller ทั้งหมดในโรงงาน ",
    title_three: "● Monitor อุณหภูมิและความชื้น ภายในโรงงาน สามารถควาบคุมได้ ±1◦C",
    desc_three: "● ควบคุมการใช้พลังงานโดยแยกประเภทของการผลิตและกลุ่มการใช้พลังงานเพื่อแสดงค่าการใช้พลังงานต่อหน่วยการผลิต",
    desc_four: "● เพื่อเปรียบเทียบประสิทธิ์ภาพการใช้พลังงาน ทำให้พนักงานสามาถรู้ถึงสถานการณ์ใช้พลังงาน ณ.ขณะนั้นว่าใช้พลังงาน)",
    desc_five: "● คุ้มค่าต่อการผลิตหรือไม่ และมี Report แจ้งปริมาณการใช้พลังงานเป็น Realtime",
    image3: "https://www.phopautomation.co.th/images/products/Control.jpg",
    desc_six: "ระบบควบคุมเครื่องจักร",
    image4: "https://www.phopautomation.co.th/images/products/Control02.jpg",
    desc_seven: "รับออกแบบ ติดตั้ง เขียนโปรแกรม ควบคุมเครื่องจักรอุตสาหกรรม ปรึกษาซ่อมบำรุงเครื่องจักร  ระบบควบคุมต่างๆ โดยวิศวกรชำนาญงานของทางบริษัท ",


  },
  {
    id: 5,
    image: "https://www.phopautomation.co.th/images/slide/chiller.png",
    date: "2 May, 2021",
    title_one: "เครื่องทำน้ำเย็น Chiller",
    desc_one: "● ระบายความร้อนด้วยอากาศ (Air Cooled Water Chiller)",
    title_two: "● ระบายความร้อนด้วยน้ำ (Water Cooled Water Chiller)",
    // desc_two: "● สายพานลำเลียง (conveyer belt) ",
    // title_three: "● สายพานกะพ้อ elevator belt mini belt conveyer wire belt",
    // desc_three: "● บริการตัดต่อสายพาน pvc belt conveyer lfda pvc pu rubber assembly line belt conveyer (pvc plastic) wire mesh belt conveyer (stainless steel)",
    // desc_four: "● สายพานลำเลียง (conveyer belt)",
    // image3: "https://www.phopautomation.co.th/images/products/Conveyor.jpg",
  },
  {
    id: 6,
    image: "https://www.phopautomation.co.th/images/products/3D.jpg",
    date: "2 May, 2021",
    title_one: "เครื่องจักร Machine",
    desc_one: "ผู้ผลิต จำหน่าย และนำเข้า เครื่องจักรอุปกรณ์และนวัตกรรมด้านการขนส่งลำเลียง ระบบจัดเก็บสินค้า ระบบชั้นวางสินค้าอุตสาหกรรม และงานโลจิสติกส์ สร้างไลน์การผลิต (Production Line) ไลน์คอนเวเยอร์ (Conveyor line) โดยมืออาชีพ อย่างครบวงจรตั้งแต่เริ่มต้นจนเสร็จสิ้น",
    // title_two: "● ติดตั้งและออกแบบสายพานลำเลียง ตามแบบทุกชนิด ทุกสเป็ค ทุกรูปแบบ ",
    // desc_two: "● สายพานลำเลียง (conveyer belt) ",
    // title_three: "● สายพานกะพ้อ elevator belt mini belt conveyer wire belt",
    // desc_three: "● บริการตัดต่อสายพาน pvc belt conveyer lfda pvc pu rubber assembly line belt conveyer (pvc plastic) wire mesh belt conveyer (stainless steel)",
    // // desc_four: "● สายพานลำเลียง (conveyer belt)",
    // image3: "https://www.phopautomation.co.th/images/products/Conveyor.jpg",
  },
  
]
export default BlogApi
